In [1]:
# starter code 

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(40)

df=pd.read_csv("upscaling.csv")    #read file.
X1=df[['Still Morning', 'Still Afternoon', 'Still Evening', 'Still Night', 'Running Morning', 'Running Afternoon', 'Running Evening', 'Running Night']]

#Checking if the dataframe contains empty cell values.
#df.isnull().values.any())    

#Output label
y=df['ADHD']

#Plot features and label in feature visual file

from sklearn.preprocessing import MinMaxScaler

#Normalize features using MinMaxScaler.
#Please see https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html for more details.
scaler = MinMaxScaler()
scaler.fit(X1)
X1 = scaler.transform(X1)

#Normalize features using MinMaxScaler.
#Please see https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html for more details.


In [2]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn import metrics
from sklearn.metrics import f1_score

X_train, X_test, y_train, y_test = train_test_split(X1, y, test_size = 0.30, 
random_state= 42)

# authroized_or_not = (y == 0) | (y == 1)
# X = X_train[authroized_or_not]
# y = y_train[authroized_or_not]


# SVM Classifier model
C = [1,10,100,1000]
y_predict = []
for x in C:
    print("When C is ", x)
    print("======================")
    print("======================")

    name = "Linear Kernel"
    print(name)
    print("=======================")
    svm_clf = SVC(kernel="linear", C=x) #using C=1
    # svm_clf.fit(X, y)
    # #predict on test data
    # #providing test data for petal length and width and testing the model.
    #Actual label is 0.
    svm_clf.fit(X_train,y_train)

    tmp = svm_clf.score(X_test,y_test)
    print("The Linear kernal returns: ", tmp)
    
    y_predict = svm_clf.predict(X_test)
    confusion_matrix = metrics.confusion_matrix(y_predict,y_test)
    print(name, "Confusion Matrix: ")
    print(confusion_matrix)
    F1 = f1_score(y_predict,y_test)
    print(name, "F1: ", F1)
    tn, fp, fn, tp = metrics.confusion_matrix(y_test, y_predict).ravel()
    print(tn, fp, fn, tp)
    print(name, "precision is: ", tp/(tp+fp))
    print(name, "recall is: ", tp/(tp+fn))
    print(name, "accuracy is: ", (tp+tn)/(tp+tn+fp+fn))
    print("-----------------------")

    name = "Poly Kernel"
    print(name)
    print("=======================")

    svm_clf = SVC(kernel='poly', degree=2,C=x) #polynomial kernel with degree 2.
    svm_clf.fit(X_train,y_train)

    tmp = svm_clf.score(X_test,y_test)
    print("The Poly kernal returns: ", tmp)

        
    y_predict = svm_clf.predict(X_test)
    confusion_matrix = metrics.confusion_matrix(y_predict,y_test)
    print(name, "Confusion Matrix: ")
    print(confusion_matrix)
    F1 = f1_score(y_predict,y_test)
    print(name, "F1: ", F1)
    tn, fp, fn, tp = metrics.confusion_matrix(y_test, y_predict).ravel()
    print(tn, fp, fn, tp)
    print(name, "precision is: ", tp/(tp+fp))
    print(name, "recall is: ", tp/(tp+fn))
    print(name, "accuracy is: ", (tp+tn)/(tp+tn+fp+fn))
    print("-----------------------")

    name = "RBF Kernel"
    print(name)
    print("=======================")
    
    svm_clf = SVC(kernel='rbf', gamma=1,C=x) #gaussian rbf kernel.
    svm_clf.fit(X_train,y_train)
    
    tmp = svm_clf.score(X_test,y_test)
    print("The RBF kernal returns: ", tmp)

    y_predict = svm_clf.predict(X_test)
    confusion_matrix = metrics.confusion_matrix(y_predict,y_test)
    print(name, "Confusion Matrix: ")
    print(confusion_matrix)
    F1 = f1_score(y_predict,y_test)
    print(name, "F1: ", F1)
    tn, fp, fn, tp = metrics.confusion_matrix(y_test, y_predict).ravel()
    print(tn, fp, fn, tp)
    print(name, "precision is: ", tp/(tp+fp))
    print(name, "recall is: ", tp/(tp+fn))
    print(name, "accuracy is: ", (tp+tn)/(tp+tn+fp+fn))
    print("-----------------------")

    


# print("The average prediction value is",round(scores.mean(),3))




When C is  1
Linear Kernel
The Linear kernal returns:  0.8181818181818182
Linear Kernel Confusion Matrix: 
[[10  2]
 [ 4 17]]
Linear Kernel F1:  0.8500000000000001
10 4 2 17
Linear Kernel precision is:  0.8095238095238095
Linear Kernel recall is:  0.8947368421052632
Linear Kernel accuracy is:  0.8181818181818182
-----------------------
Poly Kernel
The Poly kernal returns:  0.7575757575757576
Poly Kernel Confusion Matrix: 
[[10  4]
 [ 4 15]]
Poly Kernel F1:  0.7894736842105263
10 4 4 15
Poly Kernel precision is:  0.7894736842105263
Poly Kernel recall is:  0.7894736842105263
Poly Kernel accuracy is:  0.7575757575757576
-----------------------
RBF Kernel
The RBF kernal returns:  0.7575757575757576
RBF Kernel Confusion Matrix: 
[[10  4]
 [ 4 15]]
RBF Kernel F1:  0.7894736842105263
10 4 4 15
RBF Kernel precision is:  0.7894736842105263
RBF Kernel recall is:  0.7894736842105263
RBF Kernel accuracy is:  0.7575757575757576
-----------------------
When C is  10
Linear Kernel
The Linear kernal r

In [3]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
import xgboost
from xgboost import XGBClassifier
from sklearn import metrics
from sklearn.metrics import f1_score
#repeate for decision tree, random forest, XGBoost

name = "Decision Tree"
print("=======================")
clf = DecisionTreeClassifier(random_state=42)
clf.fit(X_train,y_train)
tmp = clf.score(X_test,y_test)
print("Decision Tree returns: ", tmp)
y_predict = clf.predict(X_test)
confusion_matrix = metrics.confusion_matrix(y_predict,y_test)
print("Decision Tree Confusion Matrix: ")
print(confusion_matrix)
F1 = f1_score(y_predict,y_test)
print("Decision Tree F1: ", F1)
tn, fp, fn, tp = metrics.confusion_matrix(y_test, y_predict).ravel()
print(tn, fp, fn, tp)
print(name, "precision is: ", tp/(tp+fp))
print(name, "recall is: ", tp/(tp+fn))
print(name, "accuracy is: ", (tp+tn)/(tp+tn+fp+fn))




name = "Random Forest"
print("=======================")
clf = RandomForestClassifier(random_state=42)
clf.fit(X_train,y_train)
tmp = clf.score(X_test,y_test)
print("Random Forest returns: ", tmp)

y_predict = clf.predict(X_test)
confusion_matrix = metrics.confusion_matrix(y_predict,y_test)
print(name, "Confusion Matrix: ")
print(confusion_matrix)
F1 = f1_score(y_predict,y_test)
print(name, "F1: ", F1)
tn, fp, fn, tp = metrics.confusion_matrix(y_test, y_predict).ravel()
print(tn, fp, fn, tp)
print(name, "precision is: ", tp/(tp+fp))
print(name, "recall is: ", tp/(tp+fn))
print(name, "accuracy is: ", (tp+tn)/(tp+tn+fp+fn))




name = "XGBoost"
print("=======================")
clf = XGBClassifier()
clf.fit(X_train,y_train)
tmp = tmp = clf.score(X_test,y_test)
print("XGBoost returns: ", tmp)


y_predict = clf.predict(X_test)
confusion_matrix = metrics.confusion_matrix(y_predict,y_test)
print(name, "Confusion Matrix: ")
print(confusion_matrix)
F1 = f1_score(y_predict,y_test)
print(name, "F1: ", F1)
tn, fp, fn, tp = metrics.confusion_matrix(y_test, y_predict).ravel()
print(tn, fp, fn, tp)
print(name, "precision is: ", tp/(tp+fp))
print(name, "recall is: ", tp/(tp+fn))
print(name, "accuracy is: ", (tp+tn)/(tp+tn+fp+fn))


Decision Tree returns:  0.7272727272727273
Decision Tree Confusion Matrix: 
[[10  5]
 [ 4 14]]
Decision Tree F1:  0.7567567567567567
10 4 5 14
Decision Tree precision is:  0.7777777777777778
Decision Tree recall is:  0.7368421052631579
Decision Tree accuracy is:  0.7272727272727273
Random Forest returns:  0.8484848484848485
Random Forest Confusion Matrix: 
[[12  3]
 [ 2 16]]
Random Forest F1:  0.8648648648648649
12 2 3 16
Random Forest precision is:  0.8888888888888888
Random Forest recall is:  0.8421052631578947
Random Forest accuracy is:  0.8484848484848485
XGBoost returns:  0.8484848484848485
XGBoost Confusion Matrix: 
[[12  3]
 [ 2 16]]
XGBoost F1:  0.8648648648648649
12 2 3 16
XGBoost precision is:  0.8888888888888888
XGBoost recall is:  0.8421052631578947
XGBoost accuracy is:  0.8484848484848485


In [4]:
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.losses import BinaryCrossentropy

tf.random.set_seed(40)

model = Sequential([
    Dense(units=5, activation="relu",input_shape=(8,)),
    Dense(units=3, activation="relu"),
    Dense(units=1, activation="sigmoid")])
model.compile(loss='binary_crossentropy',optimizer = 'adam',metrics=['accuracy'])
model.fit(X_train,y_train,epochs=100)
predicted = (model.predict(X_test) > 0.5).astype("int32")

# Accuracy 
Accuracy = metrics.accuracy_score(y_test, predicted)
print("Accuracy for NN:",Accuracy)

# Precision
Precision = metrics.precision_score(y_test, predicted)
print("Precision for NN:",Precision)

# Recall
Recall = metrics.recall_score(y_test, predicted)
print("Recall for NN:",Recall)

# F1 score
F1_score = metrics.f1_score(y_test, predicted)
print("F1 score for NN:",F1_score)
print()



Epoch 1/100


2023-04-14 15:11:56.854180: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


3/3 [==============================] - 1s 2ms/step - loss: 0.6495 - accuracy: 0.6486
Epoch 2/100
3/3 [==============================] - 0s 2ms/step - loss: 0.6467 - accuracy: 0.6622
Epoch 3/100
3/3 [==============================] - 0s 2ms/step - loss: 0.6444 - accuracy: 0.7027
Epoch 4/100
3/3 [==============================] - 0s 4ms/step - loss: 0.6419 - accuracy: 0.7027
Epoch 5/100
3/3 [==============================] - 0s 2ms/step - loss: 0.6399 - accuracy: 0.7027
Epoch 6/100
3/3 [==============================] - 0s 3ms/step - loss: 0.6382 - accuracy: 0.6757
Epoch 7/100
3/3 [==============================] - 0s 2ms/step - loss: 0.6364 - accuracy: 0.6757
Epoch 8/100
3/3 [==============================] - 0s 2ms/step - loss: 0.6351 - accuracy: 0.6757
Epoch 9/100
3/3 [==============================] - 0s 3ms/step - loss: 0.6335 - accuracy: 0.6622
Epoch 10/100
3/3 [==============================] - 0s 2ms/step - loss: 0.6321 - accuracy: 0.6622
Epoch 11/100
3/3 [=======================

3/3 [==============================] - 0s 1ms/step - loss: 0.5047 - accuracy: 0.8243
Epoch 85/100
3/3 [==============================] - 0s 2ms/step - loss: 0.5032 - accuracy: 0.8108
Epoch 86/100
3/3 [==============================] - 0s 2ms/step - loss: 0.5017 - accuracy: 0.8108
Epoch 87/100
3/3 [==============================] - 0s 2ms/step - loss: 0.4999 - accuracy: 0.8108
Epoch 88/100
3/3 [==============================] - 0s 2ms/step - loss: 0.4987 - accuracy: 0.8378
Epoch 89/100
3/3 [==============================] - 0s 2ms/step - loss: 0.4969 - accuracy: 0.8378
Epoch 90/100
3/3 [==============================] - 0s 2ms/step - loss: 0.4955 - accuracy: 0.8378
Epoch 91/100
3/3 [==============================] - 0s 2ms/step - loss: 0.4938 - accuracy: 0.8378
Epoch 92/100
3/3 [==============================] - 0s 2ms/step - loss: 0.4923 - accuracy: 0.8378
Epoch 93/100
3/3 [==============================] - 0s 2ms/step - loss: 0.4906 - accuracy: 0.8378
Epoch 94/100
3/3 [===============

In [5]:
model = Sequential([
    Dense(units=4, activation="relu",input_shape=(8,)),
    Dense(units=1, activation="sigmoid")])
model.compile(loss='binary_crossentropy',optimizer = 'adam',metrics=['accuracy'])
model.fit(X_train,y_train,epochs=100)
predicted = (model.predict(X_test) > 0.5).astype("int32")

# Accuracy 
Accuracy = metrics.accuracy_score(y_test, predicted)
print("Accuracy for NN:",Accuracy)

# Precision
Precision = metrics.precision_score(y_test, predicted)
print("Precision for NN:",Precision)

# Recall
Recall = metrics.recall_score(y_test, predicted)
print("Recall for NN:",Recall)

# F1 score
F1_score = metrics.f1_score(y_test, predicted)
print("F1 score for NN:",F1_score)
print()

Epoch 1/100
3/3 [==============================] - 0s 2ms/step - loss: 0.7177 - accuracy: 0.4865
Epoch 2/100
3/3 [==============================] - 0s 2ms/step - loss: 0.7163 - accuracy: 0.5135
Epoch 3/100
3/3 [==============================] - 0s 2ms/step - loss: 0.7151 - accuracy: 0.4595
Epoch 4/100
3/3 [==============================] - 0s 3ms/step - loss: 0.7139 - accuracy: 0.4324
Epoch 5/100
3/3 [==============================] - 0s 2ms/step - loss: 0.7126 - accuracy: 0.4189
Epoch 6/100
3/3 [==============================] - 0s 3ms/step - loss: 0.7113 - accuracy: 0.4054
Epoch 7/100
3/3 [==============================] - 0s 2ms/step - loss: 0.7099 - accuracy: 0.4054
Epoch 8/100
3/3 [==============================] - 0s 2ms/step - loss: 0.7089 - accuracy: 0.4054
Epoch 9/100
3/3 [==============================] - 0s 3ms/step - loss: 0.7077 - accuracy: 0.4054
Epoch 10/100
3/3 [==============================] - 0s 2ms/step - loss: 0.7067 - accuracy: 0.3919
Epoch 11/100
3/3 [===========

3/3 [==============================] - 0s 2ms/step - loss: 0.6859 - accuracy: 0.5811
Epoch 85/100
3/3 [==============================] - 0s 2ms/step - loss: 0.6858 - accuracy: 0.5811
Epoch 86/100
3/3 [==============================] - 0s 2ms/step - loss: 0.6857 - accuracy: 0.5811
Epoch 87/100
3/3 [==============================] - 0s 2ms/step - loss: 0.6856 - accuracy: 0.5811
Epoch 88/100
3/3 [==============================] - 0s 2ms/step - loss: 0.6856 - accuracy: 0.5811
Epoch 89/100
3/3 [==============================] - 0s 2ms/step - loss: 0.6855 - accuracy: 0.5811
Epoch 90/100
3/3 [==============================] - 0s 2ms/step - loss: 0.6854 - accuracy: 0.5541
Epoch 91/100
3/3 [==============================] - 0s 2ms/step - loss: 0.6853 - accuracy: 0.5811
Epoch 92/100
3/3 [==============================] - 0s 2ms/step - loss: 0.6852 - accuracy: 0.5811
Epoch 93/100
3/3 [==============================] - 0s 2ms/step - loss: 0.6852 - accuracy: 0.5811
Epoch 94/100
3/3 [===============