In [1]:
# starter code 

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(40)

df=pd.read_csv("temp.csv")    #read file.
X1=df[['Still Morning', 'Still Afternoon', 'Still Evening', 'Still Night', 'Running Morning', 'Running Afternoon', 'Running Evening', 'Running Night']]

#Checking if the dataframe contains empty cell values.
#df.isnull().values.any())    

#Output label
y=df['ADHD']

#Plot features and label in feature visual file

from sklearn.preprocessing import MinMaxScaler

#Normalize features using MinMaxScaler.
#Please see https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html for more details.
scaler = MinMaxScaler()
scaler.fit(X1)
X1 = scaler.transform(X1)

#Normalize features using MinMaxScaler.
#Please see https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html for more details.


In [2]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn import metrics
from sklearn.metrics import f1_score

X_train, X_test, y_train, y_test = train_test_split(X1, y, test_size = 0.30, 
random_state= 42)

# authroized_or_not = (y == 0) | (y == 1)
# X = X_train[authroized_or_not]
# y = y_train[authroized_or_not]


# SVM Classifier model
C = [1,10,100,1000]
y_predict = []
for x in C:
    print("When C is ", x)
    print("======================")
    print("======================")

    name = "Linear Kernel"
    print(name)
    print("=======================")
    svm_clf = SVC(kernel="linear", C=x) #using C=1
    # svm_clf.fit(X, y)
    # #predict on test data
    # #providing test data for petal length and width and testing the model.
    #Actual label is 0.
    svm_clf.fit(X_train,y_train)

    tmp = svm_clf.score(X_test,y_test)
    print("The Linear kernal returns: ", tmp)
    
    y_predict = svm_clf.predict(X_test)
    confusion_matrix = metrics.confusion_matrix(y_predict,y_test)
    print(name, "Confusion Matrix: ")
    print(confusion_matrix)
    F1 = f1_score(y_predict,y_test)
    print(name, "F1: ", F1)
    tn, fp, fn, tp = metrics.confusion_matrix(y_test, y_predict).ravel()
    print(tn, fp, fn, tp)
    print(name, "precision is: ", tp/(tp+fp))
    print(name, "recall is: ", tp/(tp+fn))
    print(name, "accuracy is: ", (tp+tn)/(tp+tn+fp+fn))
    print("-----------------------")

    name = "Poly Kernel"
    print(name)
    print("=======================")

    svm_clf = SVC(kernel='poly', degree=2,C=x) #polynomial kernel with degree 2.
    svm_clf.fit(X_train,y_train)

    tmp = svm_clf.score(X_test,y_test)
    print("The Poly kernal returns: ", tmp)

        
    y_predict = svm_clf.predict(X_test)
    confusion_matrix = metrics.confusion_matrix(y_predict,y_test)
    print(name, "Confusion Matrix: ")
    print(confusion_matrix)
    F1 = f1_score(y_predict,y_test)
    print(name, "F1: ", F1)
    tn, fp, fn, tp = metrics.confusion_matrix(y_test, y_predict).ravel()
    print(tn, fp, fn, tp)
    print(name, "precision is: ", tp/(tp+fp))
    print(name, "recall is: ", tp/(tp+fn))
    print(name, "accuracy is: ", (tp+tn)/(tp+tn+fp+fn))
    print("-----------------------")

    name = "RBF Kernel"
    print(name)
    print("=======================")
    
    svm_clf = SVC(kernel='rbf', gamma=1,C=x) #gaussian rbf kernel.
    svm_clf.fit(X_train,y_train)
    
    tmp = svm_clf.score(X_test,y_test)
    print("The RBF kernal returns: ", tmp)

    y_predict = svm_clf.predict(X_test)
    confusion_matrix = metrics.confusion_matrix(y_predict,y_test)
    print(name, "Confusion Matrix: ")
    print(confusion_matrix)
    F1 = f1_score(y_predict,y_test)
    print(name, "F1: ", F1)
    tn, fp, fn, tp = metrics.confusion_matrix(y_test, y_predict).ravel()
    print(tn, fp, fn, tp)
    print(name, "precision is: ", tp/(tp+fp))
    print(name, "recall is: ", tp/(tp+fn))
    print(name, "accuracy is: ", (tp+tn)/(tp+tn+fp+fn))
    print("-----------------------")

    


# print("The average prediction value is",round(scores.mean(),3))




When C is  1
Linear Kernel
The Linear kernal returns:  0.92
Linear Kernel Confusion Matrix: 
[[ 4  0]
 [ 2 19]]
Linear Kernel F1:  0.9500000000000001
4 2 0 19
Linear Kernel precision is:  0.9047619047619048
Linear Kernel recall is:  1.0
Linear Kernel accuracy is:  0.92
-----------------------
Poly Kernel
The Poly kernal returns:  0.96
Poly Kernel Confusion Matrix: 
[[ 5  0]
 [ 1 19]]
Poly Kernel F1:  0.9743589743589743
5 1 0 19
Poly Kernel precision is:  0.95
Poly Kernel recall is:  1.0
Poly Kernel accuracy is:  0.96
-----------------------
RBF Kernel
The RBF kernal returns:  0.88
RBF Kernel Confusion Matrix: 
[[ 3  0]
 [ 3 19]]
RBF Kernel F1:  0.9268292682926829
3 3 0 19
RBF Kernel precision is:  0.8636363636363636
RBF Kernel recall is:  1.0
RBF Kernel accuracy is:  0.88
-----------------------
When C is  10
Linear Kernel
The Linear kernal returns:  0.92
Linear Kernel Confusion Matrix: 
[[ 5  1]
 [ 1 18]]
Linear Kernel F1:  0.9473684210526315
5 1 1 18
Linear Kernel precision is:  0.94

In [3]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
import xgboost
from xgboost import XGBClassifier
from sklearn import metrics
from sklearn.metrics import f1_score
#repeate for decision tree, random forest, XGBoost

name = "Decision Tree"
print("=======================")
clf = DecisionTreeClassifier(random_state=42)
clf.fit(X_train,y_train)
tmp = clf.score(X_test,y_test)
print("Decision Tree returns: ", tmp)
y_predict = clf.predict(X_test)
confusion_matrix = metrics.confusion_matrix(y_predict,y_test)
print("Decision Tree Confusion Matrix: ")
print(confusion_matrix)
F1 = f1_score(y_predict,y_test)
print("Decision Tree F1: ", F1)
tn, fp, fn, tp = metrics.confusion_matrix(y_test, y_predict).ravel()
print(tn, fp, fn, tp)
print(name, "precision is: ", tp/(tp+fp))
print(name, "recall is: ", tp/(tp+fn))
print(name, "accuracy is: ", (tp+tn)/(tp+tn+fp+fn))




name = "Random Forest"
print("=======================")
clf = RandomForestClassifier(random_state=42)
clf.fit(X_train,y_train)
tmp = clf.score(X_test,y_test)
print("Random Forest returns: ", tmp)

y_predict = clf.predict(X_test)
confusion_matrix = metrics.confusion_matrix(y_predict,y_test)
print(name, "Confusion Matrix: ")
print(confusion_matrix)
F1 = f1_score(y_predict,y_test)
print(name, "F1: ", F1)
tn, fp, fn, tp = metrics.confusion_matrix(y_test, y_predict).ravel()
print(tn, fp, fn, tp)
print(name, "precision is: ", tp/(tp+fp))
print(name, "recall is: ", tp/(tp+fn))
print(name, "accuracy is: ", (tp+tn)/(tp+tn+fp+fn))




name = "XGBoost"
print("=======================")
clf = XGBClassifier()
clf.fit(X_train,y_train)
tmp = tmp = clf.score(X_test,y_test)
print("XGBoost returns: ", tmp)


y_predict = clf.predict(X_test)
confusion_matrix = metrics.confusion_matrix(y_predict,y_test)
print(name, "Confusion Matrix: ")
print(confusion_matrix)
F1 = f1_score(y_predict,y_test)
print(name, "F1: ", F1)
tn, fp, fn, tp = metrics.confusion_matrix(y_test, y_predict).ravel()
print(tn, fp, fn, tp)
print(name, "precision is: ", tp/(tp+fp))
print(name, "recall is: ", tp/(tp+fn))
print(name, "accuracy is: ", (tp+tn)/(tp+tn+fp+fn))


Decision Tree returns:  0.68
Decision Tree Confusion Matrix: 
[[ 6  8]
 [ 0 11]]
Decision Tree F1:  0.7333333333333334
6 0 8 11
Decision Tree precision is:  1.0
Decision Tree recall is:  0.5789473684210527
Decision Tree accuracy is:  0.68
Random Forest returns:  0.88
Random Forest Confusion Matrix: 
[[ 6  3]
 [ 0 16]]
Random Forest F1:  0.9142857142857143
6 0 3 16
Random Forest precision is:  1.0
Random Forest recall is:  0.8421052631578947
Random Forest accuracy is:  0.88
XGBoost returns:  0.8
XGBoost Confusion Matrix: 
[[ 6  5]
 [ 0 14]]
XGBoost F1:  0.8484848484848484
6 0 5 14
XGBoost precision is:  1.0
XGBoost recall is:  0.7368421052631579
XGBoost accuracy is:  0.8
