In [1]:
# starter code 

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(40)

df=pd.read_csv("upscaling.csv")    #read file.
X1=df[['Still Morning', 'Still Afternoon', 'Still Evening', 'Still Night', 'Running Morning', 'Running Afternoon', 'Running Evening', 'Running Night']]

#Checking if the dataframe contains empty cell values.
#df.isnull().values.any())    

#Output label
y=df['ADHD']

#Plot features and label in feature visual file

from sklearn.preprocessing import MinMaxScaler

#Normalize features using MinMaxScaler.
#Please see https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html for more details.
scaler = MinMaxScaler()
scaler.fit(X1)
X1 = scaler.transform(X1)

#Normalize features using MinMaxScaler.
#Please see https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html for more details.


In [2]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn import metrics
from sklearn.metrics import f1_score

X_train, X_test, y_train, y_test = train_test_split(X1, y, test_size = 0.30, 
random_state= 42)

# authroized_or_not = (y == 0) | (y == 1)
# X = X_train[authroized_or_not]
# y = y_train[authroized_or_not]


# SVM Classifier model
C = [1,10,100,1000]
y_predict = []
for x in C:
    print("When C is ", x)
    print("======================")
    print("======================")

    name = "Linear Kernel"
    print(name)
    print("=======================")
    svm_clf = SVC(kernel="linear", C=x) #using C=1
    # svm_clf.fit(X, y)
    # #predict on test data
    # #providing test data for petal length and width and testing the model.
    #Actual label is 0.
    svm_clf.fit(X_train,y_train)

    tmp = svm_clf.score(X_test,y_test)
    print("The Linear kernal returns: ", tmp)
    
    y_predict = svm_clf.predict(X_test)
    confusion_matrix = metrics.confusion_matrix(y_predict,y_test)
    print(name, "Confusion Matrix: ")
    print(confusion_matrix)
    F1 = f1_score(y_predict,y_test)
    print(name, "F1: ", F1)
    tn, fp, fn, tp = metrics.confusion_matrix(y_test, y_predict).ravel()
    print(tn, fp, fn, tp)
    print(name, "precision is: ", tp/(tp+fp))
    print(name, "recall is: ", tp/(tp+fn))
    print(name, "accuracy is: ", (tp+tn)/(tp+tn+fp+fn))
    print("-----------------------")

    name = "Poly Kernel"
    print(name)
    print("=======================")

    svm_clf = SVC(kernel='poly', degree=2,C=x) #polynomial kernel with degree 2.
    svm_clf.fit(X_train,y_train)

    tmp = svm_clf.score(X_test,y_test)
    print("The Poly kernal returns: ", tmp)

        
    y_predict = svm_clf.predict(X_test)
    confusion_matrix = metrics.confusion_matrix(y_predict,y_test)
    print(name, "Confusion Matrix: ")
    print(confusion_matrix)
    F1 = f1_score(y_predict,y_test)
    print(name, "F1: ", F1)
    tn, fp, fn, tp = metrics.confusion_matrix(y_test, y_predict).ravel()
    print(tn, fp, fn, tp)
    print(name, "precision is: ", tp/(tp+fp))
    print(name, "recall is: ", tp/(tp+fn))
    print(name, "accuracy is: ", (tp+tn)/(tp+tn+fp+fn))
    print("-----------------------")

    name = "RBF Kernel"
    print(name)
    print("=======================")
    
    svm_clf = SVC(kernel='rbf', gamma=1,C=x) #gaussian rbf kernel.
    svm_clf.fit(X_train,y_train)
    
    tmp = svm_clf.score(X_test,y_test)
    print("The RBF kernal returns: ", tmp)

    y_predict = svm_clf.predict(X_test)
    confusion_matrix = metrics.confusion_matrix(y_predict,y_test)
    print(name, "Confusion Matrix: ")
    print(confusion_matrix)
    F1 = f1_score(y_predict,y_test)
    print(name, "F1: ", F1)
    tn, fp, fn, tp = metrics.confusion_matrix(y_test, y_predict).ravel()
    print(tn, fp, fn, tp)
    print(name, "precision is: ", tp/(tp+fp))
    print(name, "recall is: ", tp/(tp+fn))
    print(name, "accuracy is: ", (tp+tn)/(tp+tn+fp+fn))
    print("-----------------------")

    


# print("The average prediction value is",round(scores.mean(),3))




When C is  1
Linear Kernel
The Linear kernal returns:  0.92
Linear Kernel Confusion Matrix: 
[[ 4  0]
 [ 2 19]]
Linear Kernel F1:  0.9500000000000001
4 2 0 19
Linear Kernel precision is:  0.9047619047619048
Linear Kernel recall is:  1.0
Linear Kernel accuracy is:  0.92
-----------------------
Poly Kernel
The Poly kernal returns:  0.96
Poly Kernel Confusion Matrix: 
[[ 5  0]
 [ 1 19]]
Poly Kernel F1:  0.9743589743589743
5 1 0 19
Poly Kernel precision is:  0.95
Poly Kernel recall is:  1.0
Poly Kernel accuracy is:  0.96
-----------------------
RBF Kernel
The RBF kernal returns:  0.88
RBF Kernel Confusion Matrix: 
[[ 3  0]
 [ 3 19]]
RBF Kernel F1:  0.9268292682926829
3 3 0 19
RBF Kernel precision is:  0.8636363636363636
RBF Kernel recall is:  1.0
RBF Kernel accuracy is:  0.88
-----------------------
When C is  10
Linear Kernel
The Linear kernal returns:  0.92
Linear Kernel Confusion Matrix: 
[[ 5  1]
 [ 1 18]]
Linear Kernel F1:  0.9473684210526315
5 1 1 18
Linear Kernel precision is:  0.94

In [3]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
import xgboost
from xgboost import XGBClassifier
from sklearn import metrics
from sklearn.metrics import f1_score
#repeate for decision tree, random forest, XGBoost

name = "Decision Tree"
print("=======================")
clf = DecisionTreeClassifier(random_state=42)
clf.fit(X_train,y_train)
tmp = clf.score(X_test,y_test)
print("Decision Tree returns: ", tmp)
y_predict = clf.predict(X_test)
confusion_matrix = metrics.confusion_matrix(y_predict,y_test)
print("Decision Tree Confusion Matrix: ")
print(confusion_matrix)
F1 = f1_score(y_predict,y_test)
print("Decision Tree F1: ", F1)
tn, fp, fn, tp = metrics.confusion_matrix(y_test, y_predict).ravel()
print(tn, fp, fn, tp)
print(name, "precision is: ", tp/(tp+fp))
print(name, "recall is: ", tp/(tp+fn))
print(name, "accuracy is: ", (tp+tn)/(tp+tn+fp+fn))




name = "Random Forest"
print("=======================")
clf = RandomForestClassifier(random_state=42)
clf.fit(X_train,y_train)
tmp = clf.score(X_test,y_test)
print("Random Forest returns: ", tmp)

y_predict = clf.predict(X_test)
confusion_matrix = metrics.confusion_matrix(y_predict,y_test)
print(name, "Confusion Matrix: ")
print(confusion_matrix)
F1 = f1_score(y_predict,y_test)
print(name, "F1: ", F1)
tn, fp, fn, tp = metrics.confusion_matrix(y_test, y_predict).ravel()
print(tn, fp, fn, tp)
print(name, "precision is: ", tp/(tp+fp))
print(name, "recall is: ", tp/(tp+fn))
print(name, "accuracy is: ", (tp+tn)/(tp+tn+fp+fn))




name = "XGBoost"
print("=======================")
clf = XGBClassifier()
clf.fit(X_train,y_train)
tmp = tmp = clf.score(X_test,y_test)
print("XGBoost returns: ", tmp)


y_predict = clf.predict(X_test)
confusion_matrix = metrics.confusion_matrix(y_predict,y_test)
print(name, "Confusion Matrix: ")
print(confusion_matrix)
F1 = f1_score(y_predict,y_test)
print(name, "F1: ", F1)
tn, fp, fn, tp = metrics.confusion_matrix(y_test, y_predict).ravel()
print(tn, fp, fn, tp)
print(name, "precision is: ", tp/(tp+fp))
print(name, "recall is: ", tp/(tp+fn))
print(name, "accuracy is: ", (tp+tn)/(tp+tn+fp+fn))


Decision Tree returns:  0.68
Decision Tree Confusion Matrix: 
[[ 6  8]
 [ 0 11]]
Decision Tree F1:  0.7333333333333334
6 0 8 11
Decision Tree precision is:  1.0
Decision Tree recall is:  0.5789473684210527
Decision Tree accuracy is:  0.68
Random Forest returns:  0.88
Random Forest Confusion Matrix: 
[[ 6  3]
 [ 0 16]]
Random Forest F1:  0.9142857142857143
6 0 3 16
Random Forest precision is:  1.0
Random Forest recall is:  0.8421052631578947
Random Forest accuracy is:  0.88
XGBoost returns:  0.8
XGBoost Confusion Matrix: 
[[ 6  5]
 [ 0 14]]
XGBoost F1:  0.8484848484848484
6 0 5 14
XGBoost precision is:  1.0
XGBoost recall is:  0.7368421052631579
XGBoost accuracy is:  0.8


In [4]:
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.losses import BinaryCrossentropy

tf.random.set_seed(40)

model = Sequential([
    Dense(units=5, activation="relu",input_shape=(8,)),
    Dense(units=3, activation="relu"),
    Dense(units=1, activation="sigmoid")])
model.compile(loss='binary_crossentropy',optimizer = 'adam',metrics=['accuracy'])
model.fit(X_train,y_train,epochs=100)
predicted = (model.predict(X_test) > 0.5).astype("int32")

# Accuracy 
Accuracy = metrics.accuracy_score(y_test, predicted)
print("Accuracy for NN:",Accuracy)

# Precision
Precision = metrics.precision_score(y_test, predicted)
print("Precision for NN:",Precision)

# Recall
Recall = metrics.recall_score(y_test, predicted)
print("Recall for NN:",Recall)

# F1 score
F1_score = metrics.f1_score(y_test, predicted)
print("F1 score for NN:",F1_score)
print()



Epoch 1/100


2023-04-06 19:07:14.202741: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


2/2 [==============================] - 1s 3ms/step - loss: 0.6561 - accuracy: 0.6316
Epoch 2/100
2/2 [==============================] - 0s 2ms/step - loss: 0.6540 - accuracy: 0.7193
Epoch 3/100
2/2 [==============================] - 0s 2ms/step - loss: 0.6525 - accuracy: 0.7368
Epoch 4/100
2/2 [==============================] - 0s 2ms/step - loss: 0.6506 - accuracy: 0.7368
Epoch 5/100
2/2 [==============================] - 0s 3ms/step - loss: 0.6494 - accuracy: 0.7544
Epoch 6/100
2/2 [==============================] - 0s 3ms/step - loss: 0.6480 - accuracy: 0.7719
Epoch 7/100
2/2 [==============================] - 0s 3ms/step - loss: 0.6465 - accuracy: 0.7719
Epoch 8/100
2/2 [==============================] - 0s 2ms/step - loss: 0.6452 - accuracy: 0.7544
Epoch 9/100
2/2 [==============================] - 0s 3ms/step - loss: 0.6438 - accuracy: 0.7895
Epoch 10/100
2/2 [==============================] - 0s 2ms/step - loss: 0.6424 - accuracy: 0.7895
Epoch 11/100
2/2 [=======================

2/2 [==============================] - 0s 4ms/step - loss: 0.5357 - accuracy: 0.8070
Epoch 85/100
2/2 [==============================] - 0s 3ms/step - loss: 0.5344 - accuracy: 0.8070
Epoch 86/100
2/2 [==============================] - 0s 5ms/step - loss: 0.5332 - accuracy: 0.8070
Epoch 87/100
2/2 [==============================] - 0s 5ms/step - loss: 0.5321 - accuracy: 0.8070
Epoch 88/100
2/2 [==============================] - 0s 4ms/step - loss: 0.5309 - accuracy: 0.8070
Epoch 89/100
2/2 [==============================] - 0s 4ms/step - loss: 0.5297 - accuracy: 0.8070
Epoch 90/100
2/2 [==============================] - 0s 4ms/step - loss: 0.5286 - accuracy: 0.8070
Epoch 91/100
2/2 [==============================] - 0s 4ms/step - loss: 0.5276 - accuracy: 0.8070
Epoch 92/100
2/2 [==============================] - 0s 3ms/step - loss: 0.5264 - accuracy: 0.8070
Epoch 93/100
2/2 [==============================] - 0s 3ms/step - loss: 0.5251 - accuracy: 0.8070
Epoch 94/100
2/2 [===============

In [5]:
model = Sequential([
    Dense(units=4, activation="relu",input_shape=(8,)),
    Dense(units=1, activation="sigmoid")])
model.compile(loss='binary_crossentropy',optimizer = 'adam',metrics=['accuracy'])
model.fit(X_train,y_train,epochs=100)
predicted = (model.predict(X_test) > 0.5).astype("int32")

# Accuracy 
Accuracy = metrics.accuracy_score(y_test, predicted)
print("Accuracy for NN:",Accuracy)

# Precision
Precision = metrics.precision_score(y_test, predicted)
print("Precision for NN:",Precision)

# Recall
Recall = metrics.recall_score(y_test, predicted)
print("Recall for NN:",Recall)

# F1 score
F1_score = metrics.f1_score(y_test, predicted)
print("F1 score for NN:",F1_score)
print()

Epoch 1/100
2/2 [==============================] - 0s 3ms/step - loss: 0.6977 - accuracy: 0.6491
Epoch 2/100
2/2 [==============================] - 0s 2ms/step - loss: 0.6970 - accuracy: 0.6667
Epoch 3/100
2/2 [==============================] - 0s 2ms/step - loss: 0.6963 - accuracy: 0.6667
Epoch 4/100
2/2 [==============================] - 0s 2ms/step - loss: 0.6956 - accuracy: 0.6667
Epoch 5/100
2/2 [==============================] - 0s 2ms/step - loss: 0.6951 - accuracy: 0.6667
Epoch 6/100
2/2 [==============================] - 0s 3ms/step - loss: 0.6945 - accuracy: 0.6667
Epoch 7/100
2/2 [==============================] - 0s 3ms/step - loss: 0.6939 - accuracy: 0.6667
Epoch 8/100
2/2 [==============================] - 0s 3ms/step - loss: 0.6933 - accuracy: 0.6667
Epoch 9/100
2/2 [==============================] - 0s 4ms/step - loss: 0.6928 - accuracy: 0.6667
Epoch 10/100
2/2 [==============================] - 0s 3ms/step - loss: 0.6922 - accuracy: 0.6667
Epoch 11/100
2/2 [===========

2/2 [==============================] - 0s 2ms/step - loss: 0.6562 - accuracy: 0.6667
Epoch 85/100
2/2 [==============================] - 0s 2ms/step - loss: 0.6558 - accuracy: 0.6667
Epoch 86/100
2/2 [==============================] - 0s 2ms/step - loss: 0.6555 - accuracy: 0.6667
Epoch 87/100
2/2 [==============================] - 0s 2ms/step - loss: 0.6550 - accuracy: 0.6667
Epoch 88/100
2/2 [==============================] - 0s 3ms/step - loss: 0.6547 - accuracy: 0.6667
Epoch 89/100
2/2 [==============================] - 0s 2ms/step - loss: 0.6544 - accuracy: 0.6667
Epoch 90/100
2/2 [==============================] - 0s 2ms/step - loss: 0.6540 - accuracy: 0.6667
Epoch 91/100
2/2 [==============================] - 0s 2ms/step - loss: 0.6536 - accuracy: 0.6667
Epoch 92/100
2/2 [==============================] - 0s 2ms/step - loss: 0.6534 - accuracy: 0.6667
Epoch 93/100
2/2 [==============================] - 0s 2ms/step - loss: 0.6529 - accuracy: 0.6667
Epoch 94/100
2/2 [===============